export const SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS config (
    chiave TEXT PRIMARY KEY,
    valore TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS aziende (
    id TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    partita_iva TEXT,
    codice_fiscale TEXT,
    indirizzo TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS fornitori (
    id TEXT PRIMARY KEY,
    ragione_sociale TEXT NOT NULL,
    partita_iva TEXT,
    codice_fiscale TEXT,
    iban TEXT,
    email TEXT,
    telefono TEXT,
    metodo_pagamento_default TEXT,
    regola_pagamento_id TEXT,
    attivo INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS regole_pagamento (
    id TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    giorni INTEGER NOT NULL DEFAULT 0,
    fine_mese INTEGER NOT NULL DEFAULT 0,
    giorni_extra INTEGER NOT NULL DEFAULT 0,
    metodo_pagamento TEXT,
    auto_pagato INTEGER NOT NULL DEFAULT 0,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS fatture_acquisto (
    id TEXT PRIMARY KEY,
    fornitore_id TEXT,
    fornitore_nome TEXT NOT NULL,
    numero TEXT NOT NULL,
    data_fattura TEXT NOT NULL,
    imponibile REAL NOT NULL DEFAULT 0,
    iva REAL NOT NULL DEFAULT 0,
    totale REAL NOT NULL DEFAULT 0,
    valuta TEXT NOT NULL DEFAULT 'EUR',
    metodo_pagamento TEXT,
    stato TEXT NOT NULL DEFAULT 'DA_VERIFICARE',
    data_pagamento TEXT,
    origine_import TEXT,
    xml_hash TEXT,
    xml_nome_file TEXT,
    documento_id TEXT,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(fornitore_nome, numero, data_fattura)
  )`,
  `CREATE TABLE IF NOT EXISTS fatture_acquisto_righe (
    id TEXT PRIMARY KEY,
    fattura_id TEXT NOT NULL,
    numero_linea INTEGER,
    codice_articolo TEXT,
    descrizione_originale TEXT NOT NULL,
    prodotto_id TEXT,
    categoria TEXT,
    quantita REAL NOT NULL DEFAULT 0,
    um TEXT,
    prezzo_unitario REAL NOT NULL DEFAULT 0,
    totale_riga REAL NOT NULL DEFAULT 0,
    aliquota_iva REAL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(fattura_id) REFERENCES fatture_acquisto(id)
  )`,
  `CREATE TABLE IF NOT EXISTS fatture_vendita (
    id TEXT PRIMARY KEY,
    cliente_nome TEXT NOT NULL,
    cliente_partita_iva TEXT,
    cliente_codice_fiscale TEXT,
    numero TEXT NOT NULL,
    data_fattura TEXT NOT NULL,
    imponibile REAL NOT NULL DEFAULT 0,
    iva REAL NOT NULL DEFAULT 0,
    totale REAL NOT NULL DEFAULT 0,
    valuta TEXT NOT NULL DEFAULT 'EUR',
    stato TEXT NOT NULL DEFAULT 'EMESSA',
    data_incasso TEXT,
    origine_import TEXT,
    xml_hash TEXT,
    xml_nome_file TEXT,
    documento_id TEXT,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(cliente_nome, numero, data_fattura)
  )`,
  `CREATE TABLE IF NOT EXISTS fatture_vendita_righe (
    id TEXT PRIMARY KEY,
    fattura_id TEXT NOT NULL,
    numero_linea INTEGER,
    codice_articolo TEXT,
    descrizione_originale TEXT NOT NULL,
    quantita REAL NOT NULL DEFAULT 0,
    um TEXT,
    prezzo_unitario REAL NOT NULL DEFAULT 0,
    totale_riga REAL NOT NULL DEFAULT 0,
    aliquota_iva REAL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(fattura_id) REFERENCES fatture_vendita(id)
  )`,
  `CREATE TABLE IF NOT EXISTS scadenze (
    id TEXT PRIMARY KEY,
    fattura_id TEXT NOT NULL,
    fornitore_id TEXT,
    data_scadenza TEXT NOT NULL,
    data_pagamento TEXT,
    importo REAL NOT NULL DEFAULT 0,
    importo_pagato REAL NOT NULL DEFAULT 0,
    stato TEXT NOT NULL DEFAULT 'APERTO',
    metodo_pagamento TEXT,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(fattura_id) REFERENCES fatture_acquisto(id)
  )`,
  `CREATE TABLE IF NOT EXISTS pagamenti (
    id TEXT PRIMARY KEY,
    scadenza_id TEXT NOT NULL,
    fattura_id TEXT,
    data_pagamento TEXT NOT NULL,
    importo REAL NOT NULL DEFAULT 0,
    metodo_pagamento TEXT,
    conto TEXT,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(scadenza_id) REFERENCES scadenze(id)
  )`,
  `CREATE TABLE IF NOT EXISTS prima_nota (
    id TEXT PRIMARY KEY,
    data_movimento TEXT NOT NULL,
    tipo TEXT NOT NULL,
    conto TEXT,
    conto_destinazione TEXT,
    categoria TEXT,
    sottocategoria TEXT,
    descrizione TEXT NOT NULL,
    importo REAL NOT NULL DEFAULT 0,
    metodo_pagamento TEXT,
    origine TEXT NOT NULL DEFAULT 'Manuale',
    riferimento_tipo TEXT,
    riferimento_id TEXT,
    fornitore_id TEXT,
    fornitore_nome TEXT,
    note TEXT,
    auto_generato INTEGER NOT NULL DEFAULT 0,
    modificabile INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS prima_nota_conti (
    id TEXT PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    tipo TEXT NOT NULL DEFAULT 'CONTO',
    attivo INTEGER NOT NULL DEFAULT 1,
    ordine INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS prima_nota_categorie (
    id TEXT PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    tipo_default TEXT,
    attivo INTEGER NOT NULL DEFAULT 1,
    ordine INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS prodotti (
    id TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    categoria TEXT,
    um_base TEXT,
    pezzi_per_cartone REAL NOT NULL DEFAULT 1,
    quantita_per_unita REAL NOT NULL DEFAULT 1,
    um_acquisto_default TEXT,
    note_conversione TEXT,
    attivo INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS prodotti_mapping (
    id TEXT PRIMARY KEY,
    descrizione_originale TEXT NOT NULL,
    fornitore_id TEXT,
    prodotto_id TEXT,
    confidenza REAL,
    pezzi_per_cartone REAL NOT NULL DEFAULT 1,
    quantita_per_unita REAL NOT NULL DEFAULT 1,
    conversione_attiva INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(descrizione_originale, fornitore_id)
  )`,
  `CREATE TABLE IF NOT EXISTS ricette (
    id TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    categoria TEXT,
    prezzo_vendita REAL NOT NULL DEFAULT 0,
    porzioni REAL NOT NULL DEFAULT 1,
    metodo_costo TEXT NOT NULL DEFAULT 'ULTIMO',
    costi_fissi_percent REAL NOT NULL DEFAULT 40,
    attiva INTEGER NOT NULL DEFAULT 1,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS ricette_ingredienti (
    id TEXT PRIMARY KEY,
    ricetta_id TEXT NOT NULL,
    prodotto_id TEXT NOT NULL,
    quantita REAL NOT NULL DEFAULT 0,
    um TEXT,
    costo_unitario_override REAL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(ricetta_id) REFERENCES ricette(id),
    FOREIGN KEY(prodotto_id) REFERENCES prodotti(id)
  )`,

  `CREATE TABLE IF NOT EXISTS incassi_cassa (
    id TEXT PRIMARY KEY,
    data_incasso TEXT NOT NULL,
    contanti REAL NOT NULL DEFAULT 0,
    pos REAL NOT NULL DEFAULT 0,
    carta_credito REAL NOT NULL DEFAULT 0,
    ticket REAL NOT NULL DEFAULT 0,
    delivery REAL NOT NULL DEFAULT 0,
    altro REAL NOT NULL DEFAULT 0,
    non_riscosso REAL NOT NULL DEFAULT 0,
    totale REAL NOT NULL DEFAULT 0,
    iva_10 REAL NOT NULL DEFAULT 0,
    iva_22 REAL NOT NULL DEFAULT 0,
    fatture_da TEXT,
    fatture_a TEXT,
    origine_import TEXT,
    nome_file TEXT,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(data_incasso)
  )`,
  `CREATE TABLE IF NOT EXISTS buste_paga (
    id TEXT PRIMARY KEY,
    mese TEXT NOT NULL,
    dipendente TEXT NOT NULL,
    lordo REAL NOT NULL DEFAULT 0,
    netto REAL NOT NULL DEFAULT 0,
    contributi_inps REAL NOT NULL DEFAULT 0,
    irpef REAL NOT NULL DEFAULT 0,
    tfr REAL NOT NULL DEFAULT 0,
    costo_azienda REAL NOT NULL DEFAULT 0,
    data_pagamento TEXT,
    metodo_pagamento TEXT,
    origine_import TEXT,
    nome_file TEXT,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(mese, dipendente)
  )`,
  `CREATE TABLE IF NOT EXISTS versamenti_f24 (
    id TEXT PRIMARY KEY,
    data_pagamento TEXT NOT NULL,
    periodo_competenza TEXT,
    tipo TEXT NOT NULL DEFAULT 'ALTRO',
    importo REAL NOT NULL DEFAULT 0,
    metodo_pagamento TEXT,
    origine_import TEXT,
    nome_file TEXT,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS documenti (
    id TEXT PRIMARY KEY,
    nome_file TEXT NOT NULL,
    tipo TEXT,
    percorso_locale TEXT,
    percorso_drive TEXT,
    hash_file TEXT,
    stato_import TEXT NOT NULL DEFAULT 'DA_IMPORTARE',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS import_log (
    id TEXT PRIMARY KEY,
    nome_file TEXT NOT NULL,
    tipo TEXT NOT NULL,
    esito TEXT NOT NULL,
    record_id TEXT,
    messaggio TEXT,
    hash_file TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS sync_log (
    id TEXT PRIMARY KEY,
    tabella TEXT NOT NULL,
    record_id TEXT NOT NULL,
    operazione TEXT NOT NULL,
    payload_json TEXT,
    stato TEXT NOT NULL DEFAULT 'DA_SYNC',
    errore TEXT,
    origin_device_id TEXT,
    cloud_revision TEXT,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    synced_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS sync_snapshots (
    id TEXT PRIMARY KEY,
    direction TEXT NOT NULL,
    source_device_id TEXT,
    cloud_revision TEXT,
    rows_total INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'OK',
    message TEXT,
    payload_hash TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`
];

export const INDEX_STATEMENTS = [
  `CREATE INDEX IF NOT EXISTS idx_fatture_acquisto_data ON fatture_acquisto(data_fattura)`,
  `CREATE INDEX IF NOT EXISTS idx_fatture_xml_hash ON fatture_acquisto(xml_hash)`,
  `CREATE INDEX IF NOT EXISTS idx_scadenze_data_stato ON scadenze(data_scadenza, stato)`,
  `CREATE INDEX IF NOT EXISTS idx_righe_prodotto ON fatture_acquisto_righe(prodotto_id)`,
  `CREATE INDEX IF NOT EXISTS idx_incassi_data ON incassi_cassa(data_incasso)`,
  `CREATE INDEX IF NOT EXISTS idx_buste_paga_mese ON buste_paga(mese)`,
  `CREATE INDEX IF NOT EXISTS idx_f24_data ON versamenti_f24(data_pagamento)`,
  `CREATE INDEX IF NOT EXISTS idx_prima_nota_data ON prima_nota(data_movimento)`,
  `CREATE INDEX IF NOT EXISTS idx_prima_nota_origine_ref ON prima_nota(origine, riferimento_tipo, riferimento_id)`,
  `CREATE INDEX IF NOT EXISTS idx_prima_nota_conti_nome ON prima_nota_conti(nome)`,
  `CREATE INDEX IF NOT EXISTS idx_prima_nota_categorie_nome ON prima_nota_categorie(nome)`,
  `CREATE INDEX IF NOT EXISTS idx_sync_log_stato ON sync_log(stato, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_sync_snapshots_created ON sync_snapshots(created_at)`
];
